name:   'Michal Dolny Blog'
url: 'http://www.michaldolny.com/blog'
author: 'Michal Dolny'

baseurl: /blog
markdown: kramdown
pygments: true
permalink: /:year/:month/:title/
paginate_path: /page:num/
excerpt_separator: "<!-- more -->"

# Setup
title: title
tagline: tagline
paginate: 2

include: ['_pages']
relative_permalinks: false