url: http://www.michaldolny.com/blog
baseurl: /blog
markdown: kramdown
pygments: true
permalink: /:year/:month/:title/
paginate_path: /page:num/
excerpt_separator: "<!-- more -->"

# Setup
title: title
tagline: tagline
paginate: 2

include: ['_pages']