url: 'http://blog.michaldolny.com'
author:
  name: 'Michał Dolny'

baseurl: ''
markdown: 'kramdown'
highlighter: pygments
permalink: /:year/:month/:title/
paginate_path: /page:num/
excerpt_separator: '<!-- more -->'

# Setup
title: 'zdolny blog'
tagline: tagline
paginate: 2

include: ['_pages']
relative_permalinks: false

safe: true