url: 'http://www.michaldolny.com/blog'
author:
  name: 'Michał Dolny'

baseurl: /blog
markdown: 'kramdown'
pygments: true
permalink: /:year/:month/:title/
paginate_path: /page:num/
excerpt_separator: "<!-- more -->"

# Setup
title: 'zdolny blog'
tagline: tagline
paginate: 2

include: ['_pages']
relative_permalinks: false

safe: true